### ISSUE TITLE
configure apiserver to verify bearer token?

### ISSUE THREAD

**Issue by dalu** [oursky/kubernetes-github-authn#5]
> Next, configure apiserver to verify bearer token using this authenticator. There are two configuration options you need to set:
> 
>     --authentication-token-webhook-config-file a kubeconfig file describing how to access the remote webhook service.
>     --authentication-token-webhook-cache-ttl how long to cache authentication decisions. Defaults to two minutes.
> 

ok. how do I do that?
I used kubeadm to install the cluster. I copied the admin.conf to .kube/config
I have that json (not sure what I should change there).
I'm logged into the master.
Now what?

**Comment by laszlocph** [comment]
These are parameters to the API server. When installing the cluster, you have to make kubeadm to pass these params to the API server at startup.

I don't have the exact solution but these are some pointers: https://github.com/kubernetes/kubeadm/issues/132 and https://stackoverflow.com/questions/41566408/restart-kubernetes-api-server-with-different-options also the Kubernetes Slack channel's kubeadm room.

**Comment by dalu** [comment]
Hmm I've added the option to `/etc/kubernetes/manifests/kube-apiserver.yaml`
and rebooted the master node
now nothing works anymore.

I give up. Thanks anyhow.
